### PR TITLE
Add Healthcheck

### PR DESCRIPTION
**Pull request by colinbruce**

### CODE REVIEW

**Comment by niallcreech** [comment]
@colinbruce this ready to be merged? IRAT requirement

**Comment by colinbruce** [comment]
@niallcreech not yet... I'm still trying to get the underlying app into a testable state, then I'll rebase this onto it.

**Comment by niallcreech** [comment]
@colinbruce no problem. Question is, do I need to defer AP from this sprint (ends on friday)? Think the rest of the works done so we're almost there and I'm chilled :)

**Comment by colinbruce** [comment]
Replacing with a different branch/heartbeat pattern

**Pull request closed without merging**
