### PR TITLE
Docker dev via runit

### PR DESCRIPTION
**Pull request by mikepea**
This is a first go at a Dockerized version of the accelerated-claims (CC) app.

It differs slightly from the docker dev prototype in prison-visits in a few main ways:

* Does not need to use socat-ssh as there are no private repos.
* There is logic in the docker start shell provisioner to handle 'vagrant provision' to recreate the image/container.
* There is a secondary process brought in -- 'strike2' -- as this is a closely coupled app that communicates via a shared dir.
* This in turn meant that the whole rails process needs to run via `runit` in dev mode. I think this is cleaner than overriding the runit startup anyway.

### CODE REVIEW

**Comment by mikepea** [comment]
Can haz merge pls? @ashb

**Comment by ashb** [comment]
@mikepea @stephenrichards okay are we happy with this all works now?

**Comment by stephenrichards** [comment]
works on MIke's laptop, not mine

On 27 February 2015 at 14:19, Ash Berlin <notifications@github.com> wrote:

> @mikepea <https://github.com/mikepea> @stephenrichards
> <https://github.com/stephenrichards> okay are we happy with this all
> works now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ministryofjustice/accelerated_claims/pull/609#issuecomment-76400946>
> .
>



-- 

--
Stephen Richards

**Comment by mikepea** [comment]
(trollface)

**Comment by pwyborn** [comment]
@mattmb Hi Would like to merge in Stephen/Mike's Docker changes please. I have successfully carried out a "Vagrant up" on this.

**Comment by pwyborn** [comment]
Hi @mattmb. Could you you please just hang-fire on this as Alex mentioned about potential issue with Strike2 (whether it should be in the same container, otherwise potential problems). Not sure if Stephen?Mike addressed this or not. I am going to liaise with Alex re this.

**Comment by pwyborn** [comment]
Hi @mattmb. Have checked Strike2 does seem to be within the same container - Alex is happy (as long as we are happy). so if we could merge it in please?

**Pull request merged**
